dist: trusty
sudo: required
language: python
  -"2.7"

env:
  GOPATH: $HOME/go
PATH: $GOPATH/bin:$PATH

install:
  - sudo apt-get update
  - sudo apt-get install python-tk
  - sudo -H pip2 install --upgrade pip
  - sudo pip install -r requirement.txt

script:
  - ./test.sh
